### ISSUE TITLE
Добавление времени трека

### ISSUE THREAD

**Issue by ayonovdenizs** [issamansur/vkpymusic#14]
При разработке бота столкнулся с проблемой, что не отдается продолжительность трека. Возможно ли это добавить в библиотеку?

**Comment by ayonovdenizs** [comment]
логов нет, но юзер выбрал трек длиной 43 минуты, и забило ОЗУ на полную.

**Comment by issamansur** [comment]
> логов нет, но юзер выбрал трек длиной 43 минуты, и забило ОЗУ на полную.

Может возникла проблема не с длительностью, а скачиванием/получением трека по ссылке такой длины?
В таком случае, проблемы с ОЗУ на Вашей стороне. Ведь запрос к ВК на получение ответа не может вызвать утечку памяти

**Comment by ayonovdenizs** [comment]
тогда, есть возможность просто добавить вместе с скачиванием, или получении треков любой имеющийся функции?

**Comment by issamansur** [comment]
> тогда, есть возможность просто добавить получение времени вместе с скачиванием, или получении треков любой имеющийся функции?
> 

В классах `Service/ServiceAsync` имеются методы для получения треков по запросу. Каждый из этих методов возвращает список объектов `Song`, в котором есть свойство `duration`, к которому Вы можете обратиться.

**Comment by issamansur** [comment]
@ayonovdenizs решили проблему?

**Comment by ayonovdenizs** [comment]
да, спасибо за ответ
