### ISSUE TITLE
Можно ли отключить логирование?

### ISSUE THREAD

**Issue by Dandelion101** [issamansur/vkpymusic#15]
![image](https://github.com/issamansur/vkpymusic/assets/123252000/10931845-af5d-409b-847f-b107e220a652)
Можно ли отключить логирование и если да то как?

**Comment by issamansur** [comment]
Добрый день. Сегодня-завтра сделаю параметр для включения/выключения логгирования и залью

**Comment by issamansur** [comment]
@Dandelion101, Необходимо только в консоли вывод убрать? В файл могу оставить?

**Comment by Dandelion101** [comment]
> @Dandelion101, Необходимо только в консоли вывод убрать? В файл могу оставить?

Да, только в консоли

**Comment by issamansur** [comment]
Попробуйте сейчас

**Comment by Dandelion101** [comment]
Спасибо
