### ISSUE TITLE
Owner ID

### ISSUE THREAD

**Issue by Shurik244** [issamansur/vkpymusic#17]
Т.к мы и так получаем токен пользователя, в чем проблема сделать функцию которая вернет VK ID аккаунта на который мы вошли

В теории мы его должны получать при входе в аккаунт, но тут я не знаю, с VK API не работал

```python
def get_user_id(token: str) -> int:
    user = requests.post('https://api.vk.com/method/users.get?v=5.199',
    headers={"Authorization": f"Bearer {token}"})
    return int(user.json()['response'][0]['id'])
```

Я не пытался делать идеальный код, поэтому доработать прийдется его вам, но уверен что этого не хватает библеотеке

**Comment by issamansur** [comment]
> Т.к мы и так получаем токен пользователя, в чем проблема сделать функцию которая вернет VK ID аккаунта на который мы вошли
> 
> В теории мы его должны получать при входе в аккаунт, но тут я не знаю, с VK API не работал
> 
> ```python
> def get_user_id(token: str) -> int:
>     user = requests.post('https://api.vk.com/method/users.get?v=5.199',
>     headers={"Authorization": f"Bearer {token}"})
>     return int(user.json()['response'][0]['id'])
> ```
> 
> Я не пытался делать идеальный код, поэтому доработать прийдется его вам, но уверен что этого не хватает библеотеке
> 

Доброго времени суток. Спасибо за обращение!
По поводу получения ВК айди:
Оно и так имеется:
`service.get_user_info()`
Возвращает объект `UserInfo`:
{
   userid, # vk id
   first_name, # имя
   last_name, # фамилия
   photo, # ссылка на аватар (фото)
   phone # номер телефона
}

**Comment by issamansur** [comment]
@Shurik244, ответил на Ваше обращение

**Comment by issamansur** [comment]
Закрываю issue в связи с неактуальностью запроса и бездействием заявителя
