### ISSUE TITLE
bitrate

### ISSUE THREAD

**Issue by 13-4dev98** [issamansur/vkpymusic#18]
Is it possible to somehow get the bitrate value of a song?

**Comment by issamansur** [comment]
I perhaps have no possibility to check this, bit I'll take a look.

**Comment by issamansur** [comment]
> > I perhaps have no possibility to check this, bit I'll take a look.
> 
> thanks for the quick response

Unfortunately, VK API doesn't provide any information about bitrate of song/audio. You can see info here:
https://dev.vk.com/en/reference/objects/audio
But you can try to use `ffmpeg` for downloading song/audio

**Comment by 13-4dev98** [comment]
> > > I perhaps have no possibility to check this, bit I'll take a look.
> > 
> > 
> > thanks for the quick response
> 
> Unfortunately, VK API doesn't provide any information about bitrate of song/audio. You can see info here: https://dev.vk.com/en/reference/objects/audio But you can try to use `ffmpeg` for downloaded song/audio

Thank you very much, I just saw the functionality of showing bitrate in @vkmusic_bot (telegram), now it’s even more interesting how they implemented it.

Can I somehow enable logging in the terminal?

**Comment by issamansur** [comment]
> > > > I perhaps have no possibility to check this, bit I'll take a look.
> > > 
> > > 
> > > thanks for the quick response
> > 
> > Unfortunately, VK API doesn't provide any information about bitrate of song/audio. You can see info here: https://dev.vk.com/en/reference/objects/audio But you can try to use `ffmpeg` for downloaded song/audio
> 
> Thank you very much, I just saw the functionality of showing bitrate in @vkmusic_bot (telegram), now it’s even more interesting how they implemented it.
> 
> Can I somehow enable logging in the terminal?

I think they download audio in `.m3u8` (it is a base format for non credentials auth or auth by client vk admin) and then use `ffmpeg` for transformation `.m3u8` to `.mp3`. And then save info about bitrate (ffnpeg can do it... Maybe)
But it is only my minds..
Try to download last release on github 3.3.0. They have logging auto. I think I did a mistake in last commit with logging settings and I have no time and physical ability to change it now.

**Comment by 13-4dev98** [comment]
> > > > > I perhaps have no possibility to check this, bit I'll take a look.
> > > > 
> > > > 
> > > > thanks for the quick response
> > > 
> > > 
> > > Unfortunately, VK API doesn't provide any information about bitrate of song/audio. You can see info here: https://dev.vk.com/en/reference/objects/audio But you can try to use `ffmpeg` for downloaded song/audio
> > 
> > 
> > Thank you very much, I just saw the functionality of showing bitrate in @vkmusic_bot (telegram), now it’s even more interesting how they implemented it.
> > Can I somehow enable logging in the terminal?
> 
> I think they download audio in `.m3u8` (it is a base format for non credentials auth or auth by client vk admin) and then use `ffmpeg` for transformation `.m3u8` to `.mp3`. And then save info about bitrate (ffnpeg can do it... Maybe) But it is only my minds.. Try to download last release on github 3.3.0. They have logging auto. I think I did a mistake in last commit with logging settings and I have no time and physical ability to change it now.

Thanks for the answers. They show the bitrate directly in the search, in addition there are several extensions for VK with bitrate,

**Comment by 13-4dev98** [comment]
> I think they download audio in `.m3u8` (it is a base format for non credentials auth or auth by client vk admin) and then use `ffmpeg` for transformation `.m3u8` to `.mp3`. And then save info about bitrate (ffnpeg can do it... Maybe)
> But it is only my minds..
> Try to download last release on github 3.3.0. They have logging auto. I think I did a mistake in last commit with logging settings and I have no time and physical ability to change it now.

managed to extract metadata from the song link and bitrate using a mutagen 

Duration: 00:03:14.85, start: 0.011995, bitrate: 320 kb/s

**Comment by issamansur** [comment]
> удалось извлечь метаданные из ссылки на песню и битрейта

Wow! Congratulations! Did you use `ffmpeg` or something else?

**Comment by 13-4dev98** [comment]
> > удалось извлечь метаданные из ссылки на песню и битрейта
> 
> Wow! Congratulations! Did you use `ffmpeg` or something else?

`ffmpeg.probe` accesses the specified URL to retrieve metadata from the stream headers, provided the server VK supports HTTP requests of the HEAD or byte-range type. It then iterates through each stream in the metadata, finds a stream where `codec_type` is `audio`, and retrieves the value of the `bit_rate` key.
