### ISSUE TITLE
Local variable 'items' is None

### ISSUE THREAD

**Issue by KiryxaTech** [issamansur/vkpymusic#19]
Ошибка происходит когда я пытаюсь найти песни пользователя. Я создал приложение в вк, включил его, но при попытке получить песни определённого существуещего пользователя я получил ошибку, что локальная переменная items равна None.

```python
# tokenReceiver = TokenReceiver(login, password)
# if tokenReceiver.auth():
#     tokenReceiver.get_token()
#     tokenReceiver.save_to_config()

token = Service.parse_config()
# Получение токена через Service.parse_config()
token = Service.parse_config()

# Строка для User-Agent, чтобы имитировать запрос от браузера
user_agent = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36"

# Создаем объект Service, передавая строку User-Agent и токен
music_service = Service(user_agent, token)

# Получаем песни пользователя с ID 618877360, ограничиваем 1 песней
user_songs = music_service.get_songs_by_userid(618877360, 1)

# Выводим полученные песни
print(user_songs)
```

Может я не правильно подставляю какие-то аргументы?

**Comment by issamansur** [comment]
Доброго времени суток. Интересный кейс, не думал, что кто-то будет использовать код так)
Полностью посмотрю ошибку завтра, но по поводу кода:
1) юзер агенты свои использовать не надо). В библиотеке есть `clients`, которые содержат в себе всю нужную информацию.
2) При авторизации через логин/пароль и сохранении токена – информация о юзер агенте, через который был выполнен вход сохраняется вместе с токеном
3) При использовании `Service.parse_config()` – сервис отдает не токен, а сервис, уже готовый к работе, перенастраивать ничего не надо. Можно сразу вызывать `get_songs_...` и т.д.
4) Ошибка с `items is None` происходит скорее всего из-за того, что ты создаёшь неверно сервис, либо же из-за того, что ты указываешь иной юзер агент. В этом случае у тебя идёт запрос к музыке без правильных токена/юзер агента, что ведёт не к корректному ответу -> некорректному парсингу (м.б. пустому) -> соответственно ошибке
5) Надеюсь из пояснений, ты поймёшь, что в коде надо изменить. Если нет - напиши, и я подскажу

**Comment by issamansur** [comment]
Я наверное понял из-за чего код был использован так: 
TokenReceiver, казалось бы получает токен и при `save_config()`сохраняет его, чтобы потом спарсить.
Но на самом деле он сохраняет информации о токене и юзер агенте в конфигурацию, из которой можно сразу создать сервис.
Это сделано из-за того, что токен работает с юзер агентом, через который был получен токен. А токен нельзя получить через любой юзер агент, только через специальные

**Comment by issamansur** [comment]
@KiryxaTech, ответил

**Comment by KiryxaTech** [comment]
Спасибо, всё понятно описано, вы очень помогли с решением вопроса.
